jQuery.noConflict();
jQuery(document).ready(function(){
	jQuery("a#resuscitation").click(function(){
		jQuery("#canvas").load("projects/resuscitation.html");
	});
	jQuery("a#green").click(function(){
		jQuery("#canvas").load("projects/green.html");
	});
	jQuery("a#golfmanager").click(function(){
		jQuery("#canvas").load("projects/golf-manager.html");
	});
	jQuery("a#personal").click(function(){
		jQuery("#canvas").load("projects/personal.html");
	});
	jQuery("a#business").click(function(){
		jQuery("#canvas").load("projects/business.html");
	});
	jQuery("a#resume").click(function(){
		jQuery("#canvas").load("projects/resume-responsive.html");
	});
	jQuery("a#apps").click(function(){
		jQuery("#canvas").load("projects/dublin-apps.html");
	});
	jQuery("a#irc").click(function(){
		jQuery("#canvas").load("projects/irc-tiles.html");
	});	
	jQuery("a#castlot").click(function(){
		jQuery("#canvas").load("projects/castlot.html");
	});	
	jQuery("a#monetago").click(function(){
		jQuery("#canvas").load("projects/monetago.html");
	});
	jQuery("a#mizunokotoba").click(function(){
		jQuery("#canvas").load("projects/mizunokotoba.html");
	});
	jQuery("a#inthepool").click(function(){
		jQuery("#canvas").load("projects/inthepool.html");
	});
	jQuery("a#chemwatch").click(function(){
		jQuery("#canvas").load("projects/chemwatch.html");
	});
  	jQuery("a#micropack").click(function(){
		jQuery("#canvas").load("projects/micropack.html");
	});
  	jQuery("a#vetiasi").click(function(){
		jQuery("#canvas").load("projects/vetiasi.html");
	});
  	jQuery("a#elegant").click(function(){
		jQuery("#canvas").load("projects/elegant.html");
	});  
  	jQuery("a#fibo").click(function(){
		jQuery("#canvas").load("projects/fibo.html");
	}); 
  	jQuery("a#lists").click(function(){
		jQuery("#canvas").load("projects/lists.html");
	}); 
  	jQuery("a#wrt").click(function(){
		jQuery("#canvas").load("projects/wrt.html");
	});   
});